version: '2'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/usr/app/
      - /usr/app/node_modules
    ports:
      - 5000:5000
    depends_on:
      - mongodb
  mongodb:
    image : mongo
    container_name: mongodb
    volumes:
    - /mongodb/database:/data/db
    ports:
    - 27017:27017
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true